export type {
  AssetsReadyRequest,
  ArenaCatalogLoadout,
  ArenaCatalogSkillId,
  ArenaAssetReadinessStages,
  ArenaContentPack,
  ArenaContentPackKind,
  ArenaError,
  ArenaGameMode,
  ArenaLoadout,
  ArenaTeamId,
  AttackBoostPackState,
  ClassId,
  ClassSwitchRequest,
  CombatEvent,
  CombatEventType,
  DuelRealmState,
  EffectState,
  EffectType,
  EngineerTurretKind,
  GameSnapshot,
  HealthPackState,
  JoinAccepted,
  JoinRequest,
  MatchAssetManifest,
  MatchPrepareRequest,
  LeaderboardEntry,
  PlayerActionState,
  PlayerInput,
  ProjectilePhase,
  ProjectileState,
  ProjectileType,
  PublicPlayer,
  RoundPhase,
  RoundState,
  SkillKey,
  TurretState
} from "./generated/arenaProtocolV1";

export type ArenaLoadoutSlot = "skillQ" | "skillE" | "skillR";

export type ArenaSkillTier = "basic" | "intermediate" | "ultimate";
